name: Deploy Bot

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          cd /home/glor/KernelGuardBot
          git pull
          /home/glor/.venv/bin/uv sync
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user restart kernelguard
